import os


def generate_code(intent, architecture):

    project_folder = "generated_project"

    frontend_path = os.path.join(
        project_folder,
        "frontend"
    )

    backend_path = os.path.join(
        project_folder,
        "backend"
    )

    database_path = os.path.join(
        project_folder,
        "database"
    )

    os.makedirs(
        frontend_path,
        exist_ok=True
    )

    os.makedirs(
        backend_path,
        exist_ok=True
    )

    os.makedirs(
        database_path,
        exist_ok=True
    )

    generated_files = []

    # Generate HTML pages
    for page in architecture["pages"]:

        file_path = os.path.join(
            frontend_path,
            f"{page}.html"
        )

        with open(
            file_path,
            "w"
        ) as file:

            file.write(f"""
<!DOCTYPE html>
<html>
<head>
    <title>{page}</title>
</head>
<body>
    <h1>{page}</h1>
    <p>Generated by AI Compiler</p>
</body>
</html>
""")

        generated_files.append(
            file_path
        )

    # Auth module
    if "login" in intent["features"]:

        auth_file = os.path.join(
            backend_path,
            "auth.py"
        )

        with open(
            auth_file,
            "w"
        ) as file:

            file.write("""
def login():
    return "User Login"
""")

        generated_files.append(
            auth_file
        )

    # Payments module
    if "payments" in intent["features"]:

        payment_file = os.path.join(
            backend_path,
            "payments.py"
        )

        with open(
            payment_file,
            "w"
        ) as file:

            file.write("""
def process_payment():
    return "Payment Success"
""")

        generated_files.append(
            payment_file
        )

    # SQL schema
    schema_file = os.path.join(
        database_path,
        "schema.sql"
    )

    with open(
        schema_file,
        "w"
    ) as file:

        file.write("""
CREATE TABLE users (
    id INT PRIMARY KEY,
    created_at TIMESTAMP
);
""")

    generated_files.append(
        schema_file
    )

    return {
        "status":
        "code_generated",

        "project_folder":
        project_folder,

        "generated_files":
        generated_files
    }